### ISSUE TITLE
massPrunable must be changed + Missing tests

### ISSUE THREAD

**Issue by afpinedac** [spatie/laravel-deleted-models#10]
I tried to send PR but it was blocked.

I think the right Implementation is 

 protected function massPrunable()
    {
        return static::where('created_at', '<=', now()->subDays(config('deleted-models.prune_after_days')));
    }

Also, the CONTRIBUTING.md file is missing. How can we do that?

**Comment by freekmurze** [comment]
The tests prove that the current behaviour is working.
